### PR TITLE
Automatically build key portions of AppImageKit

### PR DESCRIPTION
**Pull request by olekw**
- Build only the portion necessary for creating Ember AppImages
- Use the resulting AppImageKit components to create the Ember AppImage
- This will remove the requirement to install/compile AppImageKit manually
- Minor cleanup/adjustment of existing AppImage code

### CODE REVIEW

**Comment by probonopd** [comment]
Are you providing an AppImage for download and if so, where?
If not, why not?

**Comment by erikogenvik** [comment]
We do provide AppImages of the latest release at https://sourceforge.net/projects/worldforge/files/Ember%20%28OGRE%20client%29/0.7.2/

We don't currently provide AppImages of the development version, mainly because we don't have a  CI server setup.

**Comment by probonopd** [comment]
Thanks for the clarification, so I assume there is  no support needed on generating AppImage :-)

**Comment by erikogenvik** [comment]
We would be very happy for any help with working on the AppImage generation code. I haven't used it in a while, so I don't know how up to date it is. Presumably there's been developments in AppImage which we haven't kept us up to date with.
If you have more information, or are able to help out, it would be greatly appreciated.

**Pull request merged**
